name: Node CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
    - run: npm run build
    - name: Run E2E
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      with:
        args: npm run e2e
    - run: npm run package
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "out/*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: 'npm run release'
      if: startsWith(github.ref, 'refs/tags/')
      env:      
        CLIENT_ID: ${{ secrets.PUBLISHER_CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.PUBLISHER_CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.PUBLISHER_CHROME_REFRESH_TOKEN }}
        EXTENSION_ID: 'jlmafbaeoofdegohdhinkhilhclaklkp'
